import { CheckCircle2, CircleDashed, ClipboardCheck, Loader2, MessageSquare, Paperclip, Plus, Sparkles } from "lucide-react";
import React, { FormEvent, useState } from "react";
import { trpc } from "@/lib/trpc";
import { useActiveOrganization } from "@/hooks/useActiveOrganization";

const nextStatus: Record<string, { label: string; value: "in_progress" | "completed" } | null> = { proposed: { label: "Start action", value: "in_progress" }, in_progress: { label: "Mark complete", value: "completed" }, completed: null, archived: null };

export default function ActionsWorkspace() {
  const utils = trpc.useUtils();
  const tenant = useActiveOrganization();
  const organizationId = tenant.organizationId ?? 0;
  const sites = trpc.sites.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const actions = trpc.actions.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<"low" | "medium" | "high" | "critical">("medium");
  const [siteId, setSiteId] = useState<number | undefined>();
  const [impact, setImpact] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [selectedActionId, setSelectedActionId] = useState<number | null>(null);
  const [comment, setComment] = useState("");
  const [evidenceLabel, setEvidenceLabel] = useState("");
  const [evidenceReference, setEvidenceReference] = useState("");
  const [evidenceType, setEvidenceType] = useState<"note" | "url" | "attachment">("note");
  const collaboration = trpc.actions.collaboration.useQuery({ organizationId, actionId: selectedActionId ?? 0 }, { enabled: Boolean(organizationId && selectedActionId) });
  const invalidateActionEvidence = async () => { await Promise.all([utils.actions.list.invalidate({ organizationId }), utils.actions.collaboration.invalidate({ organizationId, actionId: selectedActionId ?? 0 })]); };
  const createAction = trpc.actions.create.useMutation({ onSuccess: async () => { await utils.actions.list.invalidate({ organizationId }); setTitle(""); setDescription(""); setImpact(""); setNotice("Action recorded with an audit event."); }, onError: () => setNotice("Action was not saved. Review the required fields and retry.") });
  const changeStatus = trpc.actions.updateStatus.useMutation({ onSuccess: async () => { await invalidateActionEvidence(); setNotice("Action status updated."); }, onError: () => setNotice("Action status could not be updated. Retry the operation.") });
  const addComment = trpc.actions.addComment.useMutation({ onSuccess: async () => { await invalidateActionEvidence(); setComment(""); setNotice("Action comment recorded with audit evidence."); }, onError: () => setNotice("Comment was not recorded. Retry the operation.") });
  const addEvidence = trpc.actions.addEvidence.useMutation({ onSuccess: async () => { await invalidateActionEvidence(); setEvidenceLabel(""); setEvidenceReference(""); setNotice("Action evidence reference recorded."); }, onError: () => setNotice("Evidence was not recorded. Retry the operation.") });

  if (tenant.isLoading || (Boolean(organizationId) && (sites.isLoading || actions.isLoading))) return <div className="app-loading-state"><CircleDashed className="animate-spin"/> Loading accountable work…</div>;
  if (tenant.error || sites.error || actions.error) return <section className="workspace-error"><span className="ops-eyebrow"><span /> ACTIONS UNAVAILABLE</span><h1>Accountable work could not be loaded.</h1><p>No action state is assumed when the protected query fails.</p><button onClick={() => { void sites.refetch(); void actions.refetch(); }}>Retry workspace</button></section>;
  if (!tenant.activeOrganization) return <section className="empty-workspace"><span className="ops-eyebrow"><span /> ACCOUNTABILITY STARTS WITH A TENANT</span><h1>Create a registry before an action.</h1><p>Actions are always organization-scoped and can be associated with an operational site.</p></section>;

  return <div className="ecosystem-page">
    <header className="workspace-header"><div><span className="ops-eyebrow"><span /> ACTIONS</span><h1>Turn a signal into accountable work.</h1><p>Create interventions from verified operational need, then add people’s notes and evidence references. Expected impact remains modeled, not realized.</p></div><div className="tenant-badge"><ClipboardCheck size={18}/><span>{actions.data?.length ?? 0} actions</span><b>Accountable</b></div></header>
    {notice && <div className="workbench-notice" role="status">{notice}</div>}
    <section className="actions-layout">
      <form className="action-form" onSubmit={(event: FormEvent) => { event.preventDefault(); if (organizationId) createAction.mutate({ organizationId, title, description: description || undefined, priority, siteId, expectedCarbonReductionKg: impact ? Number(impact) : undefined }); }}>
        <span className="ops-eyebrow">NEW INTERVENTION</span><h2>Record an action</h2>
        <input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Inspect HVAC schedule" aria-label="Action title" required minLength={3}/>
        <textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Evidence, scope, and operating context" aria-label="Action description"/>
        <div className="form-split"><select value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)} aria-label="Action priority"><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option><option value="critical">Critical priority</option></select><select value={siteId ?? ""} onChange={(event) => setSiteId(event.target.value ? Number(event.target.value) : undefined)} aria-label="Action site"><option value="">All sites</option>{sites.data?.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></div>
        <input type="number" min="0" step="0.1" value={impact} onChange={(event) => setImpact(event.target.value)} placeholder="Expected kgCO₂e reduction (optional)" aria-label="Expected carbon reduction"/>
        <button disabled={createAction.isPending}>{createAction.isPending ? <Loader2 className="animate-spin"/> : <Plus/>} Create action</button>
      </form>
      <div className="action-lanes">{["proposed", "in_progress", "completed"].map((status) => <section key={status}><header><span>{status.replaceAll("_", " ")}</span><b>{actions.data?.filter((action) => action.status === status).length ?? 0}</b></header>{actions.data?.filter((action) => action.status === status).map((action) => { const next = nextStatus[action.status]; return <article className={`action-card action-card--${action.priority}`} key={action.id}><span>{action.priority}</span><h3>{action.title}</h3><p>{action.description ?? "No additional evidence recorded."}</p>{action.expectedCarbonReductionKg && <small>{action.expectedCarbonReductionKg} kgCO₂e expected</small>}<div className="workspace-actions"><button onClick={() => setSelectedActionId(action.id)}>{selectedActionId === action.id ? "Viewing evidence" : "Open evidence"} <MessageSquare size={14}/></button>{next && <button onClick={() => changeStatus.mutate({ organizationId, actionId: action.id, status: next.value })} disabled={changeStatus.isPending}>{next.label} <CheckCircle2 size={14}/></button>}</div></article>; })}{!actions.data?.some((action) => action.status === status) && <p className="lane-empty">No {status.replaceAll("_", " ")} actions.</p>}</section>)}</div>
    </section>
    {selectedActionId ? <section className="workspace-panel"><header><div><span className="ops-eyebrow">ACTION COLLABORATION</span><h2>{collaboration.data?.action.title ?? "Loading action evidence"}</h2></div><Paperclip size={22}/></header>{collaboration.isLoading ? <p>Loading comments and evidence references…</p> : collaboration.error ? <p role="alert" className="form-error">Action collaboration could not be loaded. Select the action again or retry.</p> : <div className="overview-grid"><article><h3>Notes</h3>{collaboration.data?.comments.length ? <div className="compact-list">{collaboration.data.comments.map(({ comment: item, author }) => <div key={item.id}><b>{author.name ?? author.email ?? "Authenticated user"}</b><small>{new Date(item.createdAt).toLocaleString()}</small><p>{item.body}</p></div>)}</div> : <p>No collaboration notes recorded yet.</p>}<form onSubmit={(event) => { event.preventDefault(); if (selectedActionId) addComment.mutate({ organizationId, actionId: selectedActionId, body: comment }); }}><textarea aria-label="Action comment" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Record a decision, owner update, or verification step" required minLength={2}/><button disabled={addComment.isPending}>{addComment.isPending ? "Saving note…" : "Add note"}</button></form></article><article><h3>Completion evidence</h3>{collaboration.data?.evidence.length ? <div className="compact-list">{collaboration.data.evidence.map((item) => <div key={item.id}><span>{item.type.toUpperCase()}</span><b>{item.label}</b><small>{item.reference}</small></div>)}</div> : <p>No evidence references recorded yet.</p>}<form onSubmit={(event) => { event.preventDefault(); if (selectedActionId) addEvidence.mutate({ organizationId, actionId: selectedActionId, type: evidenceType, label: evidenceLabel, reference: evidenceReference }); }}><select aria-label="Evidence type" value={evidenceType} onChange={(event) => setEvidenceType(event.target.value as typeof evidenceType)}><option value="note">Note</option><option value="url">URL</option><option value="attachment">Attachment reference</option></select><input aria-label="Evidence label" value={evidenceLabel} onChange={(event) => setEvidenceLabel(event.target.value)} placeholder="e.g. Facilities inspection log" required minLength={2}/><input aria-label="Evidence reference" value={evidenceReference} onChange={(event) => setEvidenceReference(event.target.value)} placeholder="A controlled URL, storage reference, or note" required minLength={2}/><button disabled={addEvidence.isPending}>{addEvidence.isPending ? "Saving evidence…" : "Add evidence reference"}</button></form></article></div>}</section> : null}
    <section className="workspace-panel action-trust"><Sparkles size={20}/><p>Accepted recommendations can create actions with their anomaly evidence preserved. Collaboration records are tenant-scoped and audited; externally verifiable savings still require measured post-intervention evidence.</p></section>
  </div>;
}
