import React, { useMemo, useState } from "react";
import { ArrowUpRight, Bell, BrainCircuit, Building2, Calculator, ClipboardCheck, FileText, FileUp, LayoutDashboard, Radar, Settings2, ShieldCheck } from "lucide-react";
import EcoSphereMark from "@/components/EcoSphereMark";
import { startLogin } from "@/const";

const workspaces = [
  { id: "overview", title: "Operations Overview", path: "/app", category: "Operate", icon: LayoutDashboard, purpose: "The authenticated mission-control hub for EcoScore, controlled demo readiness, live evidence status, targets, freshness, and the next operational step.", interactions: "Start, advance, spike-test, or reset the explicitly simulated campus flow; then follow evidence links." },
  { id: "notifications", title: "Notification Centre", path: "/app/notifications", category: "Operate", icon: Bell, purpose: "Consolidate current tenant evidence that needs attention: open alerts, import outcomes, overdue actions, and monitoring-health exceptions.", interactions: "Review source-linked records, mark the in-app item read or unread, and open the correct protected evidence workspace." },
  { id: "registry", title: "Registry", path: "/app/registry", category: "Set up", icon: Building2, purpose: "Create the tenant’s site and meter registry, manage members, and set up the IoT gateway foundation.", interactions: "Register controlled measurement sources, manage tenant roles, and rotate device credentials." },
  { id: "data", title: "Live Data", path: "/app/data", category: "Measure", icon: FileUp, purpose: "Ingest manual readings and CSV evidence, inspect quarantine outcomes, correct records, and govern emission factors.", interactions: "Preview CSVs, commit valid rows with idempotency, inspect lineage, and retain evidence safely." },
  { id: "intelligence", title: "Intelligence", path: "/app/intelligence", category: "Decide", icon: BrainCircuit, purpose: "Inspect persisted quality checks, anomalies, alerts, forecasts, recommendations, monitoring health, and traceability.", interactions: "Run one bounded monitoring cycle, acknowledge alerts, and review evidence-backed recommendations." },
  { id: "scenarios", title: "Scenarios", path: "/app/scenarios", category: "Plan", icon: Calculator, purpose: "Calculate versioned what-if interventions, apply evidence baselines, compare options, and inspect methodology and sensitivity ranges.", interactions: "Model an intervention on the server, save it, compare options, and examine assumption limits." },
  { id: "actions", title: "Actions", path: "/app/actions", category: "Act", icon: ClipboardCheck, purpose: "Turn verified signals into assigned, approved, evidence-backed, time-bounded sustainability work.", interactions: "Record action evidence, assign an accountable tenant member, approve governance decisions, and compare post-action evidence." },
  { id: "reports", title: "Reports", path: "/app/reports", category: "Explain", icon: FileText, purpose: "Create stored evidence snapshots and export reports with factor, simulation, model, and non-certification boundaries.", interactions: "Select only persisted evidence for executive report views, CSV, JSON, and print exports." },
  { id: "presenter", title: "Presenter Mode", path: "/app/presenter", category: "Explain", icon: Radar, purpose: "Follow a six-stage, judge-ready route through tenant boundary, simulation, intelligence, scenario, action, and report evidence.", interactions: "Use ordered handoffs and claim-safe prompts during a live AIEM demonstration." },
  { id: "administration", title: "Administration", path: "/app/administration", category: "Govern", icon: Settings2, purpose: "Inspect application liveness/readiness and prepare a deployed-only scheduler trial without activating background work locally.", interactions: "Review safe deployment dependencies and configure only permitted administrative controls." },
  { id: "readiness", title: "Readiness", path: "/app/readiness", category: "Govern", icon: ShieldCheck, purpose: "Inspect the implemented product inventory, verification evidence, and explicit remaining deployment gates.", interactions: "Filter readiness work and inspect the implementation evidence behind every capability." },
] as const;

const categories = ["All", ...Array.from(new Set(workspaces.map((workspace) => workspace.category)))];

export default function EcosystemDirectory() {
  const [category, setCategory] = useState("All");
  const [selectedId, setSelectedId] = useState<(typeof workspaces)[number]["id"]>("overview");
  const visible = useMemo(() => workspaces.filter((workspace) => category === "All" || workspace.category === category), [category]);
  const selected = workspaces.find((workspace) => workspace.id === selectedId) ?? workspaces[0];
  const SelectedIcon = selected.icon;

  return <main className="directory-shell">
    <header className="directory-header"><a href="/narrative" className="brand-link" aria-label="EcoSphere AI public narrative"><EcoSphereMark /></a><nav aria-label="Public navigation"><a href="/narrative">Pilot narrative</a><a href="/">Workspace access</a></nav><button onClick={() => startLogin()}>Authenticate to open workspaces <ArrowUpRight size={15}/></button></header>
    <section className="directory-hero"><span className="ops-eyebrow"><span /> ECOSYSTEM DIRECTORY</span><h1>More than a landing page: <em>one evidence-led operating system.</em></h1><p>EcoSphere AI separates the public story from tenant-scoped operational records. The pages below are real protected workspaces; authentication is required before any tenant data, controls, or simulation state is displayed.</p><div className="directory-facts"><div><span>{workspaces.length}</span><small>protected workspaces</small></div><div><span>1</span><small>public narrative</small></div><div><span>8</span><small>step operating loop</small></div></div></section>
    <section className="directory-content" aria-label="EcoSphere workspace directory"><aside><span className="ops-eyebrow">BROWSE BY PURPOSE</span><div className="directory-filters" role="tablist" aria-label="Workspace categories">{categories.map((item) => <button key={item} role="tab" aria-selected={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div><p>Choose a category, then select a workspace card to read exactly what it does before signing in.</p></aside><div className="directory-grid">{visible.map((workspace) => { const Icon = workspace.icon; const isSelected = workspace.id === selectedId; return <button key={workspace.id} className={`directory-card ${isSelected ? "is-selected" : ""}`} onClick={() => setSelectedId(workspace.id)} aria-pressed={isSelected}><Icon size={20}/><span>{workspace.category}</span><h2>{workspace.title}</h2><p>{workspace.purpose}</p><small>View capabilities <ArrowUpRight size={13}/></small></button>; })}</div></section>
    <section className="directory-detail" aria-live="polite"><SelectedIcon size={24}/><div><span className="ops-eyebrow">SELECTED WORKSPACE · {selected.category}</span><h2>{selected.title}</h2><p>{selected.purpose}</p><p><b>Interactive capabilities:</b> {selected.interactions}</p></div><div className="directory-detail__actions"><a href={selected.path}>Open protected workspace <ArrowUpRight size={15}/></a><button onClick={() => startLogin()}>Authenticate</button></div></section>
    <section className="directory-loop"><span className="ops-eyebrow">HOW THE PAGES CONNECT</span><p><b>Registry → Live Data → Intelligence → Scenarios → Actions → Reports.</b> Operations Overview is the guided starting point; Presenter Mode is the concise judge route; Administration and Readiness are governance surfaces. Numerical outcomes remain server-calculated and evidence-bound.</p></section>
  </main>;
}
