import React from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, CircleDashed, Clock3, Gauge, Radar, RefreshCw, ShieldCheck, TrendingUp, Zap } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useActiveOrganization } from "@/hooks/useActiveOrganization";
import { useEffect, useState } from "react";

const stateVisual = { ready: CheckCircle2, waiting: CircleDashed, blocked: CircleDashed, planned: Clock3 };

function formatDate(value: Date | null | undefined) {
  return value ? new Date(value).toLocaleString() : "Not yet run";
}

export default function IntelligenceWorkspace() {
  const tenant = useActiveOrganization();
  const organizationId = tenant.organizationId ?? 0;
  const utils = trpc.useUtils();
  const readiness = trpc.intelligence.readiness.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const monitoring = trpc.analytics.overview.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const operationalHealth = trpc.monitoring.health.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const alertRouting = trpc.alertRouting.get.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const deliveryAttempts = trpc.alertRouting.deliveries.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const escalationPolicy = trpc.alertEscalation.get.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const escalations = trpc.alertEscalation.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const meters = trpc.meters.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const forecasts = trpc.forecasts.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const recommendations = trpc.recommendations.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const [expectedIntervalMinutes, setExpectedIntervalMinutes] = useState("15");
  const [staleAfterMinutes, setStaleAfterMinutes] = useState("45");
  const [targetEnabled, setTargetEnabled] = useState(false);
  const [routingEnabled, setRoutingEnabled] = useState(false);
  const [routingSeverity, setRoutingSeverity] = useState<"low" | "medium" | "high" | "critical">("high");
  const [escalationEnabled, setEscalationEnabled] = useState(false);
  const [escalationSeverity, setEscalationSeverity] = useState<"low" | "medium" | "high" | "critical">("critical");
  const [escalationAfterMinutes, setEscalationAfterMinutes] = useState("60");
  const [forecastMeterId, setForecastMeterId] = useState("");
  useEffect(() => { if (operationalHealth.data?.target) { setExpectedIntervalMinutes(String(operationalHealth.data.target.expectedIntervalMinutes)); setStaleAfterMinutes(String(operationalHealth.data.target.staleAfterMinutes)); setTargetEnabled(operationalHealth.data.target.isEnabled); } }, [operationalHealth.data?.target]);
  useEffect(() => { if (alertRouting.data) { setRoutingEnabled(alertRouting.data.isEnabled); setRoutingSeverity(alertRouting.data.minimumSeverity); } }, [alertRouting.data]);
  useEffect(() => { if (escalationPolicy.data) { setEscalationEnabled(escalationPolicy.data.isEnabled); setEscalationSeverity(escalationPolicy.data.minimumSeverity); setEscalationAfterMinutes(String(escalationPolicy.data.afterMinutes)); } }, [escalationPolicy.data]);
  useEffect(() => { if (!forecastMeterId && meters.data?.[0]) setForecastMeterId(String(meters.data[0].id)); }, [forecastMeterId, meters.data]);
  const runOnce = trpc.monitoring.runOnce.useMutation({
    onSuccess: async () => {
      await Promise.all([
        utils.analytics.overview.invalidate({ organizationId }),
        utils.monitoring.status.invalidate({ organizationId }),
        utils.intelligence.readiness.invalidate({ organizationId }),
      ]);
    },
  });
  const acknowledgeAlert = trpc.alerts.acknowledge.useMutation({
    onSuccess: async () => {
      await Promise.all([
        utils.analytics.overview.invalidate({ organizationId }),
        utils.monitoring.status.invalidate({ organizationId }),
        utils.intelligence.readiness.invalidate({ organizationId }),
      ]);
    },
  });
  const configureTarget = trpc.monitoring.configureTarget.useMutation({ onSuccess: async () => { await utils.monitoring.health.invalidate({ organizationId }); } });
  const updateRouting = trpc.alertRouting.update.useMutation({ onSuccess: async () => { await Promise.all([utils.alertRouting.get.invalidate({ organizationId }), utils.alertRouting.deliveries.invalidate({ organizationId })]); } });
  const retryRecovery = trpc.monitoring.retryRecovery.useMutation({ onSuccess: async () => { await Promise.all([utils.monitoring.health.invalidate({ organizationId }), utils.monitoring.status.invalidate({ organizationId }), utils.analytics.overview.invalidate({ organizationId })]); } });
  const updateEscalation = trpc.alertEscalation.update.useMutation({ onSuccess: async () => { await utils.alertEscalation.get.invalidate({ organizationId }); } });
  const evaluateEscalation = trpc.alertEscalation.evaluateNow.useMutation({ onSuccess: async () => { await utils.alertEscalation.list.invalidate({ organizationId }); } });
  const generateForecast = trpc.forecasts.generate.useMutation({ onSuccess: async () => { await Promise.all([utils.forecasts.list.invalidate({ organizationId }), utils.intelligence.readiness.invalidate({ organizationId })]); } });
  const generateRecommendations = trpc.recommendations.generateForOpenAnomalies.useMutation({ onSuccess: async () => { await Promise.all([utils.recommendations.list.invalidate({ organizationId }), utils.intelligence.readiness.invalidate({ organizationId })]); } });
  const updateRecommendation = trpc.recommendations.updateStatus.useMutation({ onSuccess: async () => { await utils.recommendations.list.invalidate({ organizationId }); } });
  const acceptRecommendation = trpc.recommendations.acceptAsAction.useMutation({ onSuccess: async () => { await Promise.all([utils.recommendations.list.invalidate({ organizationId }), utils.actions.list.invalidate({ organizationId })]); } });

  if (tenant.isLoading || readiness.isLoading || monitoring.isLoading || operationalHealth.isLoading || alertRouting.isLoading || deliveryAttempts.isLoading || escalationPolicy.isLoading || escalations.isLoading || meters.isLoading || forecasts.isLoading || recommendations.isLoading) return <div className="app-loading-state"><CircleDashed className="animate-spin"/> Loading monitoring evidence…</div>;
  if (tenant.error || readiness.error || monitoring.error || operationalHealth.error || alertRouting.error || deliveryAttempts.error || escalationPolicy.error || escalations.error || meters.error || forecasts.error || recommendations.error) return <section className="workspace-error"><span className="ops-eyebrow"><span /> EVIDENCE UNAVAILABLE</span><h1>Monitoring evidence could not be loaded.</h1><p>The workspace did not infer a status. Check the connection and retry the protected query.</p><button onClick={() => { void readiness.refetch(); void monitoring.refetch(); void operationalHealth.refetch(); void alertRouting.refetch(); void deliveryAttempts.refetch(); void escalationPolicy.refetch(); void escalations.refetch(); void meters.refetch(); void forecasts.refetch(); void recommendations.refetch(); }}>Retry evidence query</button></section>;
  if (!tenant.activeOrganization) return <section className="empty-workspace"><span className="ops-eyebrow"><span /> INTELLIGENCE REQUIRES EVIDENCE</span><h1>Register the data path first.</h1><p>Create a tenant, register canonical meters, and ingest validated readings before monitoring can run.</p></section>;

  const data = monitoring.data;
  const status = data?.status;
  const score = status?.latestScore;
  const openAlerts = data?.alerts.filter((item) => item.alert.status === "open") ?? [];
  return <div className="ecosystem-page">
    <header className="workspace-header"><div><span className="ops-eyebrow"><span /> INTELLIGENCE</span><h1>Monitor deterministic sustainability signals.</h1><p>Data quality, anomaly evidence, pilot carbon calculations, forecasts, and evidence-linked recommendations are persisted by the server. No LLM is used to invent numerical values.</p></div><div className="tenant-badge"><BrainCircuit size={18}/><span>Evidence first</span><b>Deterministic</b></div></header>
    <section className="overview-metrics" aria-label="Monitoring health metrics">
      <article><Gauge size={20}/><span>LATEST ECOSCORE</span><strong>{score?.score ?? "—"}</strong><small>{score ? `v${score.calculationVersion}` : "Run monitoring to create a score"}</small></article>
      <article><AlertTriangle size={20}/><span>OPEN ALERTS</span><strong>{status?.openAlertCount ?? 0}</strong><small>{openAlerts.length ? "Acknowledgement required" : "No active alert evidence"}</small></article>
      <article><ShieldCheck size={20}/><span>QUALITY REVIEW</span><strong>{(data?.qualityWarnings ?? 0) + (data?.qualityFailures ?? 0)}</strong><small>{data?.qualityFailures ?? 0} failed · {data?.qualityWarnings ?? 0} warning</small></article>
      <article><Zap size={20}/><span>PILOT CARBON</span><strong>{data?.carbonTotals.totalKgCo2e?.toFixed(1) ?? "0.0"}</strong><small>kgCO₂e from energy readings</small></article>
    </section>
    <section className="overview-grid">
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">SHORT-HORIZON FORECAST</span><h2>Generate a traceable outlook</h2></div><TrendingUp size={22}/></header><p>The pilot uses a versioned moving average, limits the horizon to 24 points, and exposes holdout error rather than claiming accuracy.</p><label>Meter<select aria-label="Forecast meter" value={forecastMeterId} onChange={(event) => setForecastMeterId(event.target.value)}><option value="">Select a meter</option>{meters.data?.map((meter) => <option key={meter.id} value={meter.id}>{meter.displayName} · {meter.canonicalUnit}</option>)}</select></label><button disabled={!forecastMeterId || generateForecast.isPending} onClick={() => generateForecast.mutate({ organizationId, meterId: Number(forecastMeterId), horizonPoints: 6 })}>{generateForecast.isPending ? "Calculating forecast…" : "Generate 6-point forecast"}</button>{generateForecast.error ? <p role="alert" className="form-error">{generateForecast.error.message}</p> : null}{generateForecast.data?.forecast.status === "insufficient_data" ? <p role="status">{generateForecast.data.forecast.insufficiencyReason}</p> : generateForecast.data ? <p role="status">Forecast generated from {generateForecast.data.forecast.inputReadingCount} reading(s). Backtest MAE: {generateForecast.data.forecast.backtest?.meanAbsoluteError ?? "not available"}.</p> : null}{forecasts.data?.[0] ? <p><b>Latest:</b> {forecasts.data[0].meter.displayName} · {forecasts.data[0].forecast.status.replaceAll("_", " ")} · {formatDate(forecasts.data[0].forecast.generatedAt)}</p> : <p>No forecast evidence is saved yet.</p>}</article>
      <article className="workspace-panel workspace-panel--wide"><header><div><span className="ops-eyebrow">EVIDENCE-LINKED RECOMMENDATIONS</span><h2>Turn open anomalies into accountable decisions</h2></div><BrainCircuit size={22}/></header><p>Recommendations are deterministic response rules bound to persisted anomaly evidence. They disclose when no approved factor or intervention scenario supports a carbon or savings estimate.</p><button disabled={generateRecommendations.isPending} onClick={() => generateRecommendations.mutate({ organizationId })}>{generateRecommendations.isPending ? "Evaluating anomaly evidence…" : "Generate from open anomalies"}</button>{generateRecommendations.error ? <p role="alert" className="form-error">{generateRecommendations.error.message}</p> : null}{recommendations.data?.length ? <div className="compact-list">{recommendations.data.slice(0, 4).map(({ recommendation, meter, action }) => { const evidence = recommendation.evidence as { scenario?: { id: number; name: string }; comparison?: { id: number; name: string }; confidenceBasis?: { scoreMeaning: string; supportingEvidence: string[]; limitations: string[] } }; return <div key={recommendation.id}><span>{recommendation.priority.toUpperCase()} · {recommendation.status.toUpperCase()}</span><b>{recommendation.title}</b><small>{meter?.displayName ?? "Meter evidence unavailable"} · anomaly #{recommendation.anomalyId ?? "—"} · confidence {(Number(recommendation.confidence) * 100).toFixed(0)}%</small><small>{recommendation.rationale}</small>{evidence.confidenceBasis ? <details><summary>Confidence evidence and limits</summary><small>{evidence.confidenceBasis.scoreMeaning}</small>{evidence.confidenceBasis.supportingEvidence.map((item) => <small key={item}>{item}</small>)}{evidence.confidenceBasis.limitations.map((item) => <small key={item}>{item}</small>)}</details> : <small>Legacy recommendation: confidence basis was not persisted under the current evidence contract.</small>}{evidence.scenario ? <small>Modeled scenario #{evidence.scenario.id}: {evidence.scenario.name}</small> : null}{evidence.comparison ? <small>Comparison #{evidence.comparison.id}: {evidence.comparison.name}</small> : null}{recommendation.status === "proposed" ? <div className="workspace-actions"><button disabled={acceptRecommendation.isPending} onClick={() => acceptRecommendation.mutate({ organizationId, recommendationId: recommendation.id })}>{acceptRecommendation.isPending ? "Creating action…" : "Accept & create action"}</button><button disabled={updateRecommendation.isPending} onClick={() => updateRecommendation.mutate({ organizationId, recommendationId: recommendation.id, status: "dismissed" })}>Dismiss</button></div> : null}{action ? <small>Linked action #{action.id}: {action.title}</small> : null}</div>; })}</div> : <p>No recommendation evidence exists. Generate only after the monitoring worker has persisted an open anomaly.</p>}</article>
    </section>
    <section className="overview-grid">
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">WORKER CONTROL</span><h2>Run monitoring once</h2></div><RefreshCw size={22}/></header><p>The control invokes the same browser-independent worker used by the protected scheduled callback. It does not start a browser loop or long-lived client process.</p><p><b>Last run:</b> {formatDate(status?.latestRun?.startedAt)} {status?.latestRun ? `(${status.latestRun.status})` : ""}</p><button className="workspace-link" disabled={runOnce.isPending} onClick={() => runOnce.mutate({ organizationId })}>{runOnce.isPending ? "Running deterministic checks…" : "Run monitoring now"} <RefreshCw size={16} className={runOnce.isPending ? "animate-spin" : ""}/></button>{runOnce.error ? <p role="alert" className="form-error">{runOnce.error.message}</p> : null}{runOnce.data ? <p role="status">Run {runOnce.data.status}: {runOnce.data.readingsScanned} newly evaluated reading{runOnce.data.readingsScanned === 1 ? "" : "s"}, {runOnce.data.anomaliesCreated} anomaly event{runOnce.data.anomaliesCreated === 1 ? "" : "s"}.</p> : null}</article>
      <article className="workspace-panel workspace-panel--signal"><header><div><span className="ops-eyebrow">ALERT LIFECYCLE</span><h2>Recent alerts</h2></div><AlertTriangle size={22}/></header>{data?.alerts.length ? <div className="compact-list">{data.alerts.slice(0, 4).map(({ alert, meter }) => <div key={alert.id}><span>{alert.severity.toUpperCase()} · {meter.displayName}</span><b>{alert.title}</b><small>{alert.status} · {formatDate(alert.createdAt)}</small>{alert.status === "open" ? <button disabled={acknowledgeAlert.isPending} onClick={() => acknowledgeAlert.mutate({ organizationId, alertId: alert.id })}>Acknowledge</button> : null}</div>)}</div> : <p>No monitoring alerts are persisted yet. A medium-or-higher deviation produces an alert after sufficient baseline readings exist.</p>}</article>
      <article className="workspace-panel workspace-panel--wide"><header><div><span className="ops-eyebrow">ANOMALY EVIDENCE</span><h2>Recent deviations</h2></div><Radar size={22}/></header>{data?.anomalies.length ? <div className="action-summary">{data.anomalies.slice(0, 4).map(({ anomaly, meter }) => <div key={anomaly.id}><span>{anomaly.severity}</span><b>{meter.displayName}: z-score {Number(anomaly.zScore).toFixed(2)}</b><small>Observed {anomaly.observedValue}; baseline {anomaly.baselineMean}; status {anomaly.status}</small></div>)}</div> : <p>No anomaly events are persisted. The detector requires three prior eligible readings for each meter and uses a transparent rolling z-score rule.</p>}</article>
    </section>
    <section className="overview-grid">
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">SCHEDULED WORKER HEALTH</span><h2>{operationalHealth.data?.state.replaceAll("_", " ") ?? "not configured"}</h2></div><ShieldCheck size={22}/></header><p>{operationalHealth.data?.target?.isEnabled ? `Expected every ${operationalHealth.data.target.expectedIntervalMinutes} minutes; stale after ${operationalHealth.data.target.staleAfterMinutes} minutes.` : "No deployed schedule is enabled. This setting records the expected production cadence; it does not create a platform schedule."}</p><p><b>Latest scheduled run:</b> {formatDate(operationalHealth.data?.latestScheduledRun?.startedAt)} {operationalHealth.data?.ageMinutes != null ? `(${operationalHealth.data.ageMinutes} minutes ago)` : ""}</p><label>Expected interval (minutes)<input aria-label="Expected monitoring interval" type="number" min="5" max="1440" value={expectedIntervalMinutes} onChange={(event) => setExpectedIntervalMinutes(event.target.value)} /></label><label>Stale after (minutes)<input aria-label="Monitoring stale threshold" type="number" min="10" max="10080" value={staleAfterMinutes} onChange={(event) => setStaleAfterMinutes(event.target.value)} /></label><label><input aria-label="Enable scheduled monitoring target" type="checkbox" checked={targetEnabled} onChange={(event) => setTargetEnabled(event.target.checked)} /> Enable expected production schedule target</label><button disabled={configureTarget.isPending} onClick={() => configureTarget.mutate({ organizationId, expectedIntervalMinutes: Number(expectedIntervalMinutes), staleAfterMinutes: Number(staleAfterMinutes), isEnabled: targetEnabled })}>{configureTarget.isPending ? "Saving target…" : "Save worker health target"}</button>{configureTarget.error ? <p role="alert" className="form-error">{configureTarget.error.message}</p> : null}</article>
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">RECOVERY QUEUE</span><h2>Retry with evidence</h2></div><RefreshCw size={22}/></header>{operationalHealth.data?.openRecoveries.length ? <div className="compact-list">{operationalHealth.data.openRecoveries.map((recovery) => <div key={recovery.id}><span>{recovery.status.toUpperCase()} · {formatDate(recovery.detectedAt)}</span><b>{recovery.reason}</b><small>{recovery.attemptCount} prior retry attempt(s)</small><button disabled={retryRecovery.isPending} onClick={() => retryRecovery.mutate({ organizationId, recoveryEventId: recovery.id })}>{retryRecovery.isPending ? "Retrying…" : "Run controlled retry"}</button></div>)}</div> : <p>No open recovery incidents are persisted. A failed worker run will create one; a successful retry resolves only the matching incident.</p>}{retryRecovery.error ? <p role="alert" className="form-error">{retryRecovery.error.message}</p> : null}</article>
      <article className="workspace-panel workspace-panel--wide"><header><div><span className="ops-eyebrow">ALERT DELIVERY POLICY</span><h2>Owner-facing channel, opt-in only</h2></div><AlertTriangle size={22}/></header><p>When enabled, only newly created alerts at or above the selected severity are sent to the project-owner notification channel. The application records delivered, failed, and suppressed outcomes; it does not claim email or campus-wide escalation.</p><label>Minimum severity<select aria-label="Alert routing minimum severity" value={routingSeverity} onChange={(event) => setRoutingSeverity(event.target.value as typeof routingSeverity)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label><input aria-label="Enable owner alert routing" type="checkbox" checked={routingEnabled} onChange={(event) => setRoutingEnabled(event.target.checked)} /> Enable project-owner notification routing</label><button disabled={updateRouting.isPending} onClick={() => updateRouting.mutate({ organizationId, minimumSeverity: routingSeverity, isEnabled: routingEnabled })}>{updateRouting.isPending ? "Saving routing…" : "Save alert routing"}</button>{updateRouting.error ? <p role="alert" className="form-error">{updateRouting.error.message}</p> : null}{deliveryAttempts.data?.length ? <div className="compact-list">{deliveryAttempts.data.slice(0, 4).map(({ attempt, alert }) => <div key={attempt.id}><span>{attempt.status.toUpperCase()} · {alert.severity}</span><b>{alert.title}</b><small>Attempt {attempt.attemptNumber} · {formatDate(attempt.requestedAt)}{attempt.errorSummary ? ` · ${attempt.errorSummary}` : ""}</small></div>)}</div> : <p>No external owner-delivery attempts have been recorded. Enable routing only after the deployed owner-notification path has been verified.</p>}</article>
      <article className="workspace-panel workspace-panel--wide"><header><div><span className="ops-eyebrow">IN-APP ESCALATION</span><h2>Create accountable work after an open-alert threshold</h2></div><Zap size={22}/></header><p>This bounded escalation path creates a sustainability action only when an eligible alert remains open beyond the configured threshold. It is not email, SMS, Slack, campus escalation, or a guarantee of external response.</p><label>Minimum severity<select aria-label="Escalation minimum severity" value={escalationSeverity} onChange={(event) => setEscalationSeverity(event.target.value as typeof escalationSeverity)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Escalate after (minutes)<input aria-label="Escalation threshold minutes" type="number" min="5" max="10080" value={escalationAfterMinutes} onChange={(event) => setEscalationAfterMinutes(event.target.value)} /></label><label><input aria-label="Enable in-app alert escalation" type="checkbox" checked={escalationEnabled} onChange={(event) => setEscalationEnabled(event.target.checked)} /> Enable in-app action escalation</label><div className="workspace-actions"><button disabled={updateEscalation.isPending} onClick={() => updateEscalation.mutate({ organizationId, minimumSeverity: escalationSeverity, afterMinutes: Number(escalationAfterMinutes), isEnabled: escalationEnabled })}>{updateEscalation.isPending ? "Saving policy…" : "Save escalation policy"}</button><button disabled={evaluateEscalation.isPending} onClick={() => evaluateEscalation.mutate({ organizationId })}>{evaluateEscalation.isPending ? "Evaluating…" : "Evaluate open alerts"}</button></div>{updateEscalation.error ? <p role="alert" className="form-error">{updateEscalation.error.message}</p> : null}{evaluateEscalation.error ? <p role="alert" className="form-error">{evaluateEscalation.error.message}</p> : null}{escalations.data?.length ? <div className="compact-list">{escalations.data.slice(0, 4).map(({ escalation, alert, action }) => <div key={escalation.id}><span>{escalation.status.toUpperCase()} · due {formatDate(escalation.dueAt)}</span><b>{alert.title}</b><small>{escalation.reason}{action ? ` · Action #${action.id}: ${action.title}` : ""}</small></div>)}</div> : <p>No escalation evidence is persisted. Policies are disabled by default and only apply to open, qualifying alerts.</p>}</article>
    </section>
    <section className="pipeline-board"><div className="pipeline-board__intro"><Radar size={30}/><div><span className="ops-eyebrow">CURRENT PIPELINE</span><h2>From source contract to monitored signal.</h2></div></div>{readiness.data?.pipeline.map((stage, index) => { const Icon = stateVisual[stage.state]; return <article className={`pipeline-stage pipeline-stage--${stage.state}`} key={stage.id}><span>0{index + 1}</span><Icon size={23}/><div><b>{stage.label}</b><p>{stage.evidence}</p></div><em>{stage.state}</em></article>; })}</section>
    <section className="workspace-panel intelligence-note"><h2>Responsible AI posture</h2><p>{data?.carbonTotals.factorLabel} The worker does not call an LLM. Any future explanation or recommendation must cite persisted evidence and cannot alter calculated values.</p></section>
  </div>;
}
