import React, { useState } from "react";
import { Activity, AlertTriangle, ArrowUpRight, Building2, CheckCircle2, ClipboardCheck, Database, FileText, FileUp, Gauge, ListChecks, Play, Radio, RotateCcw, Settings2, Target, Zap } from "lucide-react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { useActiveOrganization } from "@/hooks/useActiveOrganization";
import { utcDateBoundary } from "@/lib/utcDates";

function relativeTime(value: Date | null | undefined) {
  if (!value) return "No reading recorded";
  const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60_000));
  return minutes < 1 ? "Just now" : `${minutes} min ago`;
}

function dateInputValue(value: Date) {
  return value.toISOString().slice(0, 10);
}

export default function OperationsOverview() {
  const [, navigate] = useLocation();
  const organization = useActiveOrganization();
  const organizationId = organization.organizationId ?? 0;
  const overviewQuery = trpc.operations.overview.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const readingsQuery = trpc.readings.recent.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const actionsQuery = trpc.actions.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const monitoringQuery = trpc.monitoring.status.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const demoQuery = trpc.demo.status.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const targetAssessmentQuery = trpc.targets.assessment.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const meterFreshnessQuery = trpc.analytics.meterFreshness.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const ecoScoreExplanationQuery = trpc.analytics.ecoScoreExplanation.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const metersQuery = trpc.meters.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const maintenanceQuery = trpc.maintenanceWindows.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const operatingCalendarQuery = trpc.operatingCalendarWindows.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const qualityRulesQuery = trpc.dataQualityRules.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const scenariosQuery = trpc.scenarios.list.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const reportSnapshotsQuery = trpc.reports.snapshots.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const utils = trpc.useUtils();
  const [demoNotice, setDemoNotice] = useState<string | null>(null);
  const [targetNotice, setTargetNotice] = useState<string | null>(null);
  const [targetType, setTargetType] = useState<"energy" | "water" | "waste" | "carbon" | "ecoscore">("energy");
  const [targetLabel, setTargetLabel] = useState("Monthly energy ceiling");
  const [targetValue, setTargetValue] = useState("500");
  const [targetStart, setTargetStart] = useState(() => dateInputValue(new Date()));
  const [targetEnd, setTargetEnd] = useState(() => dateInputValue(new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)));
  const [maintenanceMeterId, setMaintenanceMeterId] = useState<number | undefined>();
  const [maintenanceLabel, setMaintenanceLabel] = useState("Planned meter maintenance");
  const [maintenanceReason, setMaintenanceReason] = useState("Planned inspection or equipment work.");
  const [maintenanceStart, setMaintenanceStart] = useState(() => dateInputValue(new Date()));
  const [maintenanceEnd, setMaintenanceEnd] = useState(() => dateInputValue(new Date()));
  const [calendarMeterId, setCalendarMeterId] = useState<number | undefined>();
  const [calendarLabel, setCalendarLabel] = useState("Weekday operating hours");
  const [calendarTimezone, setCalendarTimezone] = useState("Asia/Kolkata");
  const [calendarWeekdays, setCalendarWeekdays] = useState<number[]>([1, 2, 3, 4, 5]);
  const [calendarStartMinute, setCalendarStartMinute] = useState("540");
  const [calendarEndMinute, setCalendarEndMinute] = useState("1080");
  const [ruleResource, setRuleResource] = useState<"energy" | "water" | "waste" | "fuel" | "renewable">("energy");
  const [ruleCeiling, setRuleCeiling] = useState("1000000");
  const [ruleFutureMinutes, setRuleFutureMinutes] = useState("5");

  const refreshDemoEvidence = async () => {
    await Promise.all([
      utils.demo.status.invalidate({ organizationId }),
      utils.operations.overview.invalidate({ organizationId }),
      utils.readings.recent.invalidate({ organizationId }),
      utils.monitoring.status.invalidate({ organizationId }),
      utils.analytics.overview.invalidate({ organizationId }),
      utils.intelligence.readiness.invalidate({ organizationId }),
      utils.recommendations.list.invalidate({ organizationId }),
      utils.targets.assessment.invalidate({ organizationId }),
      utils.analytics.meterFreshness.invalidate({ organizationId }),
      utils.analytics.ecoScoreExplanation.invalidate({ organizationId }),
    ]);
  };
  const startDemo = trpc.demo.start.useMutation({ onSuccess: async (result) => { setDemoNotice(`Simulation started: ${result.readingsAccepted} explicitly simulated baseline readings were persisted and evaluated.`); await refreshDemoEvidence(); } });
  const advanceDemo = trpc.demo.advance.useMutation({ onSuccess: async (result) => { setDemoNotice(`Cycle ${result.session.cycle} advanced: ${result.readingsAccepted} simulated readings were evaluated by the server worker.`); await refreshDemoEvidence(); } });
  const injectSpike = trpc.demo.injectHvacSpike.useMutation({ onSuccess: async (result) => { setDemoNotice(`Controlled HVAC spike injected: ${result.readingsAccepted} explicitly simulated reading was evaluated. Review Intelligence for the alert and recommendation evidence.`); await refreshDemoEvidence(); } });
  const resetDemo = trpc.demo.reset.useMutation({ onSuccess: async (result) => { setDemoNotice(`Demo reset: ${result.resetSummary?.supersededReadingCount ?? 0} simulated readings were superseded; non-demo tenant evidence was retained.`); await refreshDemoEvidence(); } });
  const createTarget = trpc.targets.create.useMutation({ onSuccess: async () => { setTargetNotice("Target saved. Attainment and freshness use current accepted tenant evidence only."); await utils.targets.assessment.invalidate({ organizationId }); } });
  const createMaintenance = trpc.maintenanceWindows.create.useMutation({ onSuccess: async () => { setDemoNotice("Maintenance window saved. Matching anomalies remain recorded; only alert creation is suppressed within the selected meter interval."); await utils.maintenanceWindows.list.invalidate({ organizationId }); } });
  const createOperatingCalendar = trpc.operatingCalendarWindows.create.useMutation({ onSuccess: async () => { setDemoNotice("Operating calendar saved. Future monitoring separates configured operating and off-hours baselines; it does not suppress readings, findings, anomalies, alerts, carbon, or EcoScore evidence."); await utils.operatingCalendarWindows.list.invalidate({ organizationId }); } });
  const setOperatingCalendarActive = trpc.operatingCalendarWindows.setActive.useMutation({ onSuccess: async () => { await utils.operatingCalendarWindows.list.invalidate({ organizationId }); } });
  const saveQualityRule = trpc.dataQualityRules.upsert.useMutation({ onSuccess: async () => { setDemoNotice("Future reading evaluations will use the saved rule version. Existing findings remain historical evidence."); await utils.dataQualityRules.list.invalidate({ organizationId }); } });

  if (organization.isLoading) return <div className="app-loading-state"><Activity className="animate-spin" /> Loading workspace…</div>;
  if (organization.error) return <section className="app-error-state" role="alert"><AlertTriangle size={24} /><div><h1>Tenant access is unavailable.</h1><p>Confirm your authenticated session and tenant membership, then refresh the workspace.</p></div></section>;
  if (!organization.activeOrganization) return <section className="empty-workspace"><span className="ops-eyebrow"><span /> FIRST OPERATIONAL STEP</span><h1>Start with a tenant boundary.</h1><p>Create your organization, register its first site, and define the meter units that live data must satisfy.</p><button onClick={() => navigate("/app/registry")}>Open registry <ArrowUpRight size={16} /></button></section>;

  const overview = overviewQuery.data;
  const monitoring = monitoringQuery.data;
  const activeActions = actionsQuery.data?.filter((item) => item.status === "in_progress") ?? [];
  const protectedDataUnavailable = overviewQuery.error || readingsQuery.error || actionsQuery.error || monitoringQuery.error || demoQuery.error || meterFreshnessQuery.error;
  const demoSession = demoQuery.data?.session;
  const canOperateDemo = ["owner", "manager"].includes(organization.activeOrganization.membership.role);
  const demoBusy = startDemo.isPending || advanceDemo.isPending || injectSpike.isPending || resetDemo.isPending;
  const jumpToGuidedDemo = () => document.getElementById("guided-campus-simulation")?.scrollIntoView({ behavior: "smooth", block: "start" });
  const operatingSteps = [
    { id: "setup", label: "Set up", title: "Register a canonical meter", detail: "Create the tenant site and meter boundary before accepting sustainability evidence.", path: "/app/registry", action: "Open Registry", complete: overview?.meterCount ? true : overviewQuery.data ? false : null },
    { id: "measure", label: "Measure", title: "Record accepted evidence", detail: "Add a manual reading, CSV import, or controlled simulated baseline.", path: "/app/data", action: "Open Live Data", complete: overview?.readingCount ? true : overviewQuery.data ? false : null },
    { id: "detect", label: "Detect", title: "Persist a monitored signal", detail: "Run a bounded server monitoring cycle, then inspect quality, anomaly, alert, forecast, and recommendation evidence.", path: "/app/intelligence", action: "Open Intelligence", complete: monitoring?.latestRun ? true : monitoringQuery.data ? false : null },
    { id: "simulate", label: "Simulate", title: "Save a modeled intervention", detail: "Use only server-authoritative scenarios with declared assumptions and disclosed pilot factors.", path: "/app/scenarios", action: "Open Scenarios", complete: scenariosQuery.data ? scenariosQuery.data.length > 0 : null },
    { id: "act", label: "Act", title: "Assign accountable work", detail: "Record a scoped action, target date, approval, and evidence without implying automated delivery.", path: "/app/actions", action: "Open Actions", complete: actionsQuery.data ? actionsQuery.data.length > 0 : null },
    { id: "explain", label: "Explain", title: "Preserve a report snapshot", detail: "Select stored evidence for an exportable executive report with methodology and non-certification disclosures.", path: "/app/reports", action: "Open Reports", complete: reportSnapshotsQuery.data ? reportSnapshotsQuery.data.length > 0 : null },
  ];
  const nextOperatingStep = operatingSteps.find((step) => step.complete === false) ?? operatingSteps.find((step) => step.complete === null) ?? null;
  return <div className="ecosystem-page">
    <header className="workspace-header"><div><span className="ops-eyebrow"><span /> OPERATIONS OVERVIEW</span><h1>{organization.activeOrganization.organization.name}</h1><p>One authenticated view of the records that power the sustainability operating loop.</p></div><div className="tenant-badge"><Building2 size={18} /><span>{organization.activeOrganization.membership.role}</span><b>Tenant scoped</b></div></header>
    {protectedDataUnavailable && <div className="workbench-notice" role="alert"><AlertTriangle size={18} /> Some protected operational evidence is unavailable. The overview preserves unknown values instead of inferring an empty tenant state.</div>}
    <section className="workspace-panel operating-loop-guide" aria-label="Your operating loop">
      <header><div><span className="ops-eyebrow">FIRST-USE OPERATING LOOP</span><h2>Move through the product with evidence, not guesswork.</h2></div><ListChecks size={22}/></header>
      <p>Each step reflects only stored tenant evidence. A check means the relevant record exists; it does not certify campus performance, actual savings, or a completed external workflow.</p>
      <ol>{operatingSteps.map((step) => <li key={step.id} className={step.complete === true ? "complete" : step.complete === null ? "checking" : "next"}><span>{step.complete === true ? "✓" : step.complete === null ? "…" : step.label.slice(0, 1)}</span><div><small>{step.label.toUpperCase()} · {step.complete === true ? "evidence recorded" : step.complete === null ? "checking evidence" : "next record needed"}</small><b>{step.title}</b><p>{step.detail}</p></div><button type="button" onClick={() => navigate(step.path)}>{step.action}<ArrowUpRight size={15}/></button></li>)}</ol>
      {nextOperatingStep ? <div className="operating-loop-guide__next"><div><span>NEXT USEFUL STEP</span><b>{nextOperatingStep.title}</b><small>{nextOperatingStep.detail}</small></div><button type="button" onClick={() => navigate(nextOperatingStep.path)}>Continue the loop <ArrowUpRight size={16}/></button></div> : <div className="operating-loop-guide__next operating-loop-guide__next--complete"><div><span>CORE LOOP RECORDS PRESENT</span><b>Review the evidence chain before making a decision.</b><small>Stored records exist across setup, evidence, intelligence, scenarios, actions, and reports; their individual limitations still apply.</small></div><button type="button" onClick={() => navigate("/app/presenter")}>Open Presenter Mode <ArrowUpRight size={16}/></button></div>}
      {!canOperateDemo && <p className="muted">You can inspect every listed workspace. Controlled simulation creation and reset remain limited to tenant owners and managers.</p>}
    </section>
    <section className="workspace-panel first-run-checklist" aria-label="Guided demo first-run checklist"><header><div><span className="ops-eyebrow">DEMO READINESS</span><h2>Run the judge flow with a clear evidence boundary.</h2></div><ClipboardCheck size={22}/></header><p>Use this only for the presentation sequence. Guided steps create explicitly <b>simulated</b> tenant evidence; manual or imported records remain operational evidence and are not reset.</p><ol><li className={demoSession ? "complete" : "pending"}><b>1. Prepare the controlled baseline</b><span>{demoSession ? `Session #${demoSession.id} is ${demoSession.status.replaceAll("_", " ")}.` : "No simulated session is active yet."}</span></li><li className={demoSession?.cycle ? "complete" : "pending"}><b>2. Advance one normal cycle</b><span>{demoSession?.cycle ? `${demoSession.cycle} server-evaluated simulated cycle${demoSession.cycle === 1 ? "" : "s"} recorded.` : "This creates the normal before-state."}</span></li><li className={demoSession?.status === "spike_injected" ? "complete" : "pending"}><b>3. Inject the HVAC spike</b><span>{demoSession?.status === "spike_injected" ? "Controlled spike evidence is ready for review." : "The anomaly, alert, and recommendation are generated only after this explicit step."}</span></li><li className={monitoring?.latestRun ? "complete" : "pending"}><b>4. Inspect the persisted decision evidence</b><span>{monitoring?.latestRun ? "Open Intelligence to inspect stored quality, anomaly, alert, recommendation, and action links." : "The server worker has not yet produced monitored evidence."}</span></li></ol>{canOperateDemo ? <button type="button" className="workspace-link" onClick={jumpToGuidedDemo}>Open guided demo controls <ArrowUpRight size={16}/></button> : <p className="muted">A tenant owner or manager can operate the simulated demo controls. This checklist remains visible for presentation context.</p>}</section>
    <section className="overview-metrics" aria-label="Operational tenant metrics">
      <article><Database size={20}/><span>REGISTERED METERS</span><strong>{overview?.meterCount ?? "—"}</strong><small>canonical source boundaries</small></article>
      <article><Radio size={20}/><span>VALIDATED READINGS</span><strong>{overview?.readingCount ?? "—"}</strong><small>{relativeTime(overview?.latestReadingAt)}</small></article>
      <article><ClipboardCheck size={20}/><span>ACTIVE ACTIONS</span><strong>{overview?.activeActionCount ?? "—"}</strong><small>{overview ? `${overview.actionCount} total tracked actions` : "action evidence unavailable"}</small></article>
      <article><Gauge size={20}/><span>ECOSCORE</span><strong>{monitoring?.latestScore?.score ?? "—"}</strong><small>{monitoringQuery.error ? "monitoring status unavailable" : monitoring?.latestRun ? `${monitoring.latestRun.status} · ${monitoring.openAlertCount} open alert${monitoring.openAlertCount === 1 ? "" : "s"}` : "run monitoring to create a score"}</small></article>
    </section>
    <section className="workspace-panel target-panel" aria-label="EcoScore explanation">
      <header><div><span className="ops-eyebrow">ECOSCORE EXPLANATION</span><h2>Inspect the persisted score, not an opaque rating.</h2></div><Gauge size={22}/></header>
      {ecoScoreExplanationQuery.isLoading ? <p role="status">Loading persisted EcoScore evidence…</p> : ecoScoreExplanationQuery.error ? <p className="form-error" role="alert">EcoScore explanation is unavailable. No component is inferred.</p> : ecoScoreExplanationQuery.data ? <><p><b>{ecoScoreExplanationQuery.data.snapshot.score}/100</b> · {ecoScoreExplanationQuery.data.snapshot.calculationVersion} · recorded {new Date(ecoScoreExplanationQuery.data.snapshot.computedAt).toLocaleString()}</p><p>{ecoScoreExplanationQuery.data.formula}</p><div className="target-panel__grid">{ecoScoreExplanationQuery.data.penalties.map((item) => <article key={item.id} className="target-panel__item"><span>{item.label.toUpperCase()}</span><strong>{item.value === null ? "Not persisted" : `${item.value} ${item.unit}`}</strong><small>{item.evidence}</small></article>)}</div><div className="compact-list">{ecoScoreExplanationQuery.data.evidence.map((item) => <div key={item.id}><span>{item.label}</span><b>{item.value === null ? "Not persisted" : `${item.value}${item.unit ? ` ${item.unit}` : ""}`}</b></div>)}</div><p className="muted">{ecoScoreExplanationQuery.data.disclosure}</p></> : <p>No persisted EcoScore exists yet. Run the monitored pipeline after accepted evidence is available; the interface will not manufacture a score explanation.</p>}
    </section>
    <section id="guided-campus-simulation" className="workspace-panel demo-simulation-panel" aria-label="Guided Campus Simulation">
      <header><div><span className="ops-eyebrow">GUIDED CAMPUS SIMULATION</span><h2>Show the monitoring loop with controlled evidence.</h2></div><Play size={22}/></header>
      <p>This creates a tenant-scoped <b>simulated</b> AIEM fixture, invokes the server-owned worker for each bounded step, and never represents the records as live campus telemetry. It does not start an always-on browser loop or a production scheduler.</p>
      {demoNotice ? <p className="workbench-notice" role="status" aria-live="polite">{demoNotice}</p> : null}
      {demoQuery.isLoading ? <p role="status">Loading simulation state…</p> : demoQuery.error ? <p className="form-error" role="alert">Simulation state is unavailable. Refresh this workspace before retrying.</p> : demoSession ? <div className="demo-simulation-panel__state"><span>SESSION #{demoSession.id} · {demoSession.status.replaceAll("_", " ")} · cycle {demoSession.cycle}</span><small>All generated readings are explicitly simulated and reset only affects this session.</small></div> : <div className="demo-simulation-panel__state"><span>NO ACTIVE DEMO SESSION</span><small>Start a new guided fixture when you are ready to demonstrate the full controlled sequence.</small></div>}
      {canOperateDemo ? <div className="workspace-actions">
        {!demoSession || demoSession.status === "reset" ? <button disabled={demoBusy} onClick={() => startDemo.mutate({ organizationId })}>{startDemo.isPending ? "Preparing baseline…" : <><Play size={16}/> Start guided demo</>}</button> : null}
        {demoSession?.status === "running" ? <><button disabled={demoBusy} onClick={() => advanceDemo.mutate({ organizationId })}>{advanceDemo.isPending ? "Advancing cycle…" : <><Activity size={16}/> Advance normal cycle</>}</button><button disabled={demoBusy} onClick={() => injectSpike.mutate({ organizationId })}>{injectSpike.isPending ? "Injecting spike…" : <><Zap size={16}/> Inject HVAC spike</>}</button></> : null}
        {demoSession && demoSession.status !== "reset" ? <button className="workspace-link" disabled={demoBusy} onClick={() => resetDemo.mutate({ organizationId })}>{resetDemo.isPending ? "Resetting demo…" : <><RotateCcw size={16}/> Reset demo</>}</button> : null}
      </div> : <p className="muted">Only tenant owners and managers can create, advance, inject, or reset simulated tenant evidence.</p>}
      {(startDemo.error || advanceDemo.error || injectSpike.error || resetDemo.error) ? <p className="form-error" role="alert">{startDemo.error?.message ?? advanceDemo.error?.message ?? injectSpike.error?.message ?? resetDemo.error?.message}</p> : null}
    </section>
    <section className="workspace-panel target-panel" aria-label="Sustainability targets and freshness">
      <header><div><span className="ops-eyebrow">TARGETS & FRESHNESS</span><h2>Measure progress against a declared operating target.</h2></div><Target size={22}/></header>
      <p>Resource and carbon targets are lower-is-better; EcoScore is higher-is-better. Freshness reflects the latest accepted evidence in the target window, not a claimed live integration.</p>
      {targetNotice ? <p className="workbench-notice" role="status">{targetNotice}</p> : null}
      {targetAssessmentQuery.isLoading ? <p role="status">Assessing target evidence…</p> : targetAssessmentQuery.error ? <p className="form-error" role="alert">Target evidence is unavailable. No attainment status is inferred.</p> : targetAssessmentQuery.data?.length ? <div className="target-panel__grid">{targetAssessmentQuery.data.map((item) => <article key={item.target.id} className={`target-panel__item target-panel__item--${item.assessment.state}`}><span>{item.target.targetType.toUpperCase()} · {item.direction.replace("_", " ")}</span><b>{item.target.label}</b><strong>{item.achievedValue === null ? "—" : `${Number(item.achievedValue).toFixed(1)} / `}{Number(item.target.targetValue).toFixed(1)} {item.target.unit}</strong><small>{item.assessment.state.replaceAll("_", " ")} · {item.assessment.freshness}{item.assessment.ageHours === null ? "" : ` · ${Math.round(item.assessment.ageHours)}h old`}</small></article>)}</div> : <p>No active targets are recorded. Add a time-bounded target before showing attainment in a presentation.</p>}
      {canOperateDemo ? <details className="target-panel__create"><summary>Set a tenant-wide target</summary><form onSubmit={(event) => { event.preventDefault(); createTarget.mutate({ organizationId, targetType, label: targetLabel, targetValue: Number(targetValue), windowStart: utcDateBoundary(targetStart, "start"), windowEnd: utcDateBoundary(targetEnd, "end") }); }}><label>Metric<select aria-label="Target metric" value={targetType} onChange={(event) => setTargetType(event.target.value as typeof targetType)}><option value="energy">Energy (kWh)</option><option value="water">Water (m³)</option><option value="waste">Waste (kg)</option><option value="carbon">Carbon (kgCO2e)</option><option value="ecoscore">EcoScore</option></select></label><label>Label<input aria-label="Target label" value={targetLabel} onChange={(event) => setTargetLabel(event.target.value)} required minLength={3}/></label><label>Value<input aria-label="Target value" type="number" min="0.0001" step="0.1" value={targetValue} onChange={(event) => setTargetValue(event.target.value)} required/></label><label>Window starts<input aria-label="Target window start" type="date" value={targetStart} onChange={(event) => setTargetStart(event.target.value)} required/></label><label>Window ends<input aria-label="Target window end" type="date" value={targetEnd} onChange={(event) => setTargetEnd(event.target.value)} required/></label><button disabled={createTarget.isPending}>{createTarget.isPending ? "Saving target…" : "Save target"}</button></form>{createTarget.error ? <p className="form-error" role="alert">{createTarget.error.message}</p> : null}</details> : <p className="muted">Only tenant owners and managers can set targets. Members can inspect current assessed evidence.</p>}
    </section>
    <section className="workspace-panel target-panel" aria-label="Meter freshness board">
      <header><div><span className="ops-eyebrow">EVIDENCE CADENCE</span><h2>Meter Freshness Board</h2></div><Radio size={22}/></header>
      <p>Fresh means a latest accepted, non-superseded reading within 24 hours; aging is 24–72 hours; stale is older than 72 hours. “No accepted evidence” is never treated as current telemetry.</p>
      {meterFreshnessQuery.isLoading ? <p role="status">Assessing meter freshness…</p> : meterFreshnessQuery.error ? <p className="form-error" role="alert">Meter freshness is unavailable. No current-data conclusion is inferred.</p> : meterFreshnessQuery.data?.length ? <div className="target-panel__grid">{meterFreshnessQuery.data.map(({ meter, latestAcceptedObservedAt, freshness }) => <article key={meter.id} className={`target-panel__item target-panel__item--${freshness.state}`}><span>{meter.resourceType.toUpperCase()} · {meter.canonicalUnit}</span><b>{meter.displayName}</b><strong>{freshness.state.replaceAll("_", " ")}</strong><small>{latestAcceptedObservedAt ? `${Math.round(freshness.ageHours ?? 0)}h old · ${new Date(latestAcceptedObservedAt).toLocaleString()}` : "No accepted reading recorded"}</small><small>{freshness.disclosure}</small></article>)}</div> : <p>No active meters are registered for this tenant. Register a canonical measurement source before assessing evidence cadence.</p>}
    </section>
    <section className="workspace-panel target-panel" aria-label="Maintenance windows">
      <header><div><span className="ops-eyebrow">PLANNED WORK BOUNDARY</span><h2>Maintenance windows</h2></div><Settings2 size={22}/></header>
      <p>A time-bounded maintenance window suppresses alert creation only for its selected meter. Readings, data-quality findings, anomalies, score effects, recommendations, and the suppression audit record remain available for inspection.</p>
      {maintenanceQuery.isLoading ? <p role="status">Loading maintenance windows…</p> : maintenanceQuery.error ? <p className="form-error" role="alert">Maintenance-window evidence is unavailable.</p> : maintenanceQuery.data?.length ? <div className="target-panel__grid">{maintenanceQuery.data.map(({ window, meter }) => <article key={window.id} className="target-panel__item"><span>{meter.resourceType.toUpperCase()} · {meter.displayName}</span><b>{window.label}</b><strong>{new Date(window.windowStart).toLocaleString()} → {new Date(window.windowEnd).toLocaleString()}</strong><small>{window.reason}</small><small>Alert suppression only; evidence retention remains active.</small></article>)}</div> : <p>No maintenance windows are recorded. Do not use a window to erase an inconvenient alert—use it only for planned, time-bounded meter work.</p>}
      {canOperateDemo ? <details className="target-panel__create"><summary>Record a planned maintenance window</summary><form onSubmit={(event) => { event.preventDefault(); if (!maintenanceMeterId) { setDemoNotice("Select a tenant meter before recording a maintenance window."); return; } createMaintenance.mutate({ organizationId, meterId: maintenanceMeterId, label: maintenanceLabel, reason: maintenanceReason, windowStart: utcDateBoundary(maintenanceStart, "start"), windowEnd: utcDateBoundary(maintenanceEnd, "end") }); }}><label>Meter<select aria-label="Maintenance meter" value={maintenanceMeterId ?? ""} onChange={(event) => setMaintenanceMeterId(event.target.value ? Number(event.target.value) : undefined)} required><option value="">Select active meter</option>{metersQuery.data?.filter((meter) => meter.isActive).map((meter) => <option key={meter.id} value={meter.id}>{meter.displayName} · {meter.resourceType}</option>)}</select></label><label>Window label<input aria-label="Maintenance label" value={maintenanceLabel} onChange={(event) => setMaintenanceLabel(event.target.value)} required minLength={3}/></label><label>Reason<textarea aria-label="Maintenance reason" value={maintenanceReason} onChange={(event) => setMaintenanceReason(event.target.value)} required minLength={3}/></label><label>Window starts<input aria-label="Maintenance window start" type="date" value={maintenanceStart} onChange={(event) => setMaintenanceStart(event.target.value)} required/></label><label>Window ends<input aria-label="Maintenance window end" type="date" value={maintenanceEnd} onChange={(event) => setMaintenanceEnd(event.target.value)} required/></label><button disabled={createMaintenance.isPending}>{createMaintenance.isPending ? "Saving maintenance window…" : "Save maintenance window"}</button></form>{createMaintenance.error ? <p className="form-error" role="alert">{createMaintenance.error.message}</p> : null}</details> : <p className="muted">Only tenant owners and managers can record maintenance windows. Members can inspect the suppression boundary.</p>}
    </section>
    <section className="workspace-panel target-panel" aria-label="Operating calendars">
      <header><div><span className="ops-eyebrow">CONTEXTUAL MONITORING BASELINE</span><h2>Operating calendars</h2></div><Settings2 size={22}/></header>
      <p>Operating calendars are opt-in recurring local hours for a selected meter. Future monitoring keeps every source and quality record, but separates its anomaly baseline into configured operating versus outside-configured-hours evidence. It never suppresses alerts, carbon calculations, recommendations, or EcoScore effects.</p>
      {operatingCalendarQuery.isLoading ? <p role="status">Loading operating-calendar evidence…</p> : operatingCalendarQuery.error ? <p className="form-error" role="alert">Operating-calendar evidence is unavailable. The monitoring worker remains unconfigured for this optional contextual boundary.</p> : operatingCalendarQuery.data?.length ? <div className="target-panel__grid">{operatingCalendarQuery.data.map(({ window, meter }) => <article key={window.id} className="target-panel__item"><span>{meter.resourceType.toUpperCase()} · {meter.displayName}</span><b>{window.label}</b><strong>{window.isActive ? "active contextual baseline" : "inactive — not applied"}</strong><small>{window.timezone} · days {window.weekdays.join(", ")} · {String(Math.floor(window.startMinuteLocal / 60)).padStart(2, "0")}:{String(window.startMinuteLocal % 60).padStart(2, "0")}–{String(Math.floor(window.endMinuteLocal / 60)).padStart(2, "0")}:{String(window.endMinuteLocal % 60).padStart(2, "0")}</small>{canOperateDemo ? <button className="workspace-link" disabled={setOperatingCalendarActive.isPending} onClick={() => setOperatingCalendarActive.mutate({ organizationId, windowId: window.id, isActive: !window.isActive })}>{window.isActive ? "Deactivate calendar" : "Activate calendar"}</button> : null}</article>)}</div> : <p>No operating calendar is configured. Existing monitoring uses its original unsegmented meter history until a manager explicitly defines local operating hours.</p>}
      {canOperateDemo ? <details className="target-panel__create"><summary>Define recurring operating hours</summary><form onSubmit={(event) => { event.preventDefault(); if (!calendarMeterId) { setDemoNotice("Select a tenant meter before defining operating hours."); return; } createOperatingCalendar.mutate({ organizationId, meterId: calendarMeterId, label: calendarLabel, timezone: calendarTimezone, weekdays: calendarWeekdays, startMinuteLocal: Number(calendarStartMinute), endMinuteLocal: Number(calendarEndMinute) }); }}><label>Meter<select aria-label="Operating calendar meter" value={calendarMeterId ?? ""} onChange={(event) => setCalendarMeterId(event.target.value ? Number(event.target.value) : undefined)} required><option value="">Select active meter</option>{metersQuery.data?.filter((meter) => meter.isActive).map((meter) => <option key={meter.id} value={meter.id}>{meter.displayName} · {meter.resourceType}</option>)}</select></label><label>Calendar label<input aria-label="Operating calendar label" value={calendarLabel} onChange={(event) => setCalendarLabel(event.target.value)} required minLength={3}/></label><label>IANA timezone<input aria-label="Operating calendar timezone" value={calendarTimezone} onChange={(event) => setCalendarTimezone(event.target.value)} required/></label><fieldset><legend>Local weekdays</legend>{[[0, "Sun"], [1, "Mon"], [2, "Tue"], [3, "Wed"], [4, "Thu"], [5, "Fri"], [6, "Sat"]].map(([day, label]) => <label key={day}><input type="checkbox" checked={calendarWeekdays.includes(day as number)} onChange={() => setCalendarWeekdays((current) => current.includes(day as number) ? current.filter((value) => value !== day) : [...current, day as number].sort())}/>{label}</label>)}</fieldset><label>Local start minute (0–1439)<input aria-label="Operating calendar start minute" type="number" min="0" max="1439" value={calendarStartMinute} onChange={(event) => setCalendarStartMinute(event.target.value)} required/></label><label>Local end minute (1–1440)<input aria-label="Operating calendar end minute" type="number" min="1" max="1440" value={calendarEndMinute} onChange={(event) => setCalendarEndMinute(event.target.value)} required/></label><button disabled={createOperatingCalendar.isPending}>{createOperatingCalendar.isPending ? "Saving calendar…" : "Save operating calendar"}</button></form>{createOperatingCalendar.error ? <p className="form-error" role="alert">{createOperatingCalendar.error.message}</p> : null}</details> : <p className="muted">Only tenant owners and managers can configure contextual monitoring boundaries. Members can inspect applied calendar evidence.</p>}
    </section>
    <section className="workspace-panel target-panel" aria-label="Data quality rule profiles">
      <header><div><span className="ops-eyebrow">PROSPECTIVE VALIDATION POLICY</span><h2>Data-quality rule profiles</h2></div><ClipboardCheck size={22}/></header>
      <p>Profiles apply only to future monitoring evaluations. Each stored finding retains its original rule details, so changing a policy does not rewrite historical evidence.</p>
      {qualityRulesQuery.isLoading ? <p role="status">Loading validation policies…</p> : qualityRulesQuery.data?.length ? <div className="target-panel__grid">{qualityRulesQuery.data.map((profile) => <article key={profile.id} className="target-panel__item"><span>{profile.resourceType.toUpperCase()} · VERSION {profile.version}</span><strong>Ceiling {Number(profile.highValueCeiling).toLocaleString()}</strong><small>Future tolerance: {profile.futureToleranceMinutes} min · last updated {new Date(profile.updatedAt).toLocaleString()}</small></article>)}</div> : <p>No tenant override is stored. The deterministic pilot safety ceiling and five-minute future tolerance remain active until a manager saves a prospective profile.</p>}
      {canOperateDemo ? <details className="target-panel__create"><summary>Set a prospective rule profile</summary><form onSubmit={(event) => { event.preventDefault(); saveQualityRule.mutate({ organizationId, resourceType: ruleResource, highValueCeiling: Number(ruleCeiling), futureToleranceMinutes: Number(ruleFutureMinutes) }); }}><label>Resource<select aria-label="Rule resource" value={ruleResource} onChange={(event) => setRuleResource(event.target.value as typeof ruleResource)}><option value="energy">Energy</option><option value="water">Water</option><option value="waste">Waste</option><option value="fuel">Fuel</option><option value="renewable">Renewable</option></select></label><label>High-value ceiling<input aria-label="High value ceiling" type="number" min="0.0001" value={ruleCeiling} onChange={(event) => setRuleCeiling(event.target.value)} required/></label><label>Future tolerance (minutes)<input aria-label="Future tolerance minutes" type="number" min="0" max="1440" value={ruleFutureMinutes} onChange={(event) => setRuleFutureMinutes(event.target.value)} required/></label><button disabled={saveQualityRule.isPending}>{saveQualityRule.isPending ? "Saving profile…" : "Save prospective profile"}</button></form>{saveQualityRule.error ? <p className="form-error" role="alert">{saveQualityRule.error.message}</p> : null}</details> : <p className="muted">Only tenant owners and managers can set future validation boundaries. Existing policy records remain visible to members.</p>}
    </section>
    <section className="overview-grid">
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">NEXT USEFUL STEP</span><h2>{overview?.meterCount ? overview?.readingCount ? monitoring?.latestRun ? "Review monitored sustainability signals." : "Turn verified data into a monitored signal." : "Send the first validated reading." : "Register canonical measurement sources."}</h2></div><Settings2 size={22}/></header><p>{overview?.meterCount ? overview?.readingCount ? monitoring?.latestRun ? "The latest deterministic run has persisted operational evidence. Open Intelligence to inspect its score, quality results, anomalies, and alerts." : "The registry and data foundation are active. Run the deterministic monitoring worker from Intelligence to create inspected signals." : "Your meters are registered. Use Live Data to record a first source-backed measurement." : "Define a site and meter in the Registry before any incoming data can be trusted."}</p><button className="workspace-link" onClick={() => navigate(overview?.meterCount ? overview?.readingCount ? "/app/intelligence" : "/app/data" : "/app/registry")}>Continue the loop <ArrowUpRight size={16}/></button></article>
      <article className="workspace-panel workspace-panel--signal"><header><div><span className="ops-eyebrow">CURRENT DATA EVIDENCE</span><h2>Recent readings</h2></div><FileUp size={22}/></header>{readingsQuery.isLoading ? <p role="status">Loading protected readings…</p> : readingsQuery.error ? <p role="alert">Reading evidence is unavailable. No empty-state conclusion is inferred.</p> : readingsQuery.data?.length ? <div className="compact-list">{readingsQuery.data.slice(0, 4).map(({ reading, meter }) => <div key={reading.id}><span>{meter.displayName}</span><b>{reading.value} {reading.unit}</b><small>{new Date(reading.observedAt).toLocaleString()}</small></div>)}</div> : <p>No readings are stored for this tenant. This is expected until the first validated intake occurs.</p>}<button className="workspace-link" onClick={() => navigate("/app/data")}>Open Live Data <ArrowUpRight size={16}/></button></article>
      <article className="workspace-panel workspace-panel--wide"><header><div><span className="ops-eyebrow">ACCOUNTABLE WORK</span><h2>Actions in motion</h2></div>{monitoring?.openAlertCount ? <AlertTriangle size={22}/> : <CheckCircle2 size={22}/>}</header>{actionsQuery.isLoading ? <p role="status">Loading accountable work…</p> : actionsQuery.error ? <p role="alert">Action evidence is unavailable. No empty-state conclusion is inferred.</p> : activeActions.length ? <div className="action-summary">{activeActions.map((action) => <div key={action.id}><span>{action.priority}</span><b>{action.title}</b><small>{action.expectedCarbonReductionKg ? `${action.expectedCarbonReductionKg} kgCO₂e expected` : "Impact estimate not recorded"}</small></div>)}</div> : <p>{monitoring?.openAlertCount ? `${monitoring.openAlertCount} open monitored alert${monitoring.openAlertCount === 1 ? " requires" : "s require"} accountable review in Intelligence.` : "No action is currently in progress. Add a scoped intervention when a validated signal needs accountable follow-through."}</p>}<button className="workspace-link" onClick={() => navigate(monitoring?.openAlertCount ? "/app/intelligence" : "/app/actions")}>{monitoring?.openAlertCount ? "Review alerts" : "Manage actions"} <ArrowUpRight size={16}/></button></article>
    </section>
  </div>;
}
