import React from "react";
import { ArrowUpRight, CheckCircle2, CircleAlert, ClipboardCheck, FileText, Gauge, Sparkles } from "lucide-react";

const stages = [
  { id: "setup", title: "1. Establish the tenant evidence boundary", detail: "Open Operations Overview. Confirm the tenant, source registry, Meter Freshness Board, and whether evidence is operational or explicitly simulated.", route: "/app", action: "Open Operations Overview", state: "Required before any sustainability conclusion" },
  { id: "monitor", title: "2. Run the controlled monitoring loop", detail: "Use Guided Campus Simulation only when demonstrating. Start the labelled fixture, advance a normal cycle, then inject the HVAC spike. The server worker evaluates each bounded step.", route: "/app", action: "Open guided simulation", state: "Simulation is deterministic test evidence, never live campus telemetry" },
  { id: "detect", title: "3. Inspect persisted intelligence evidence", detail: "Show the quality finding, anomaly, alert, recommendation, forecast rationale, and traceability timeline. Explain links only where persisted records establish them.", route: "/app/intelligence", action: "Open Intelligence", state: "No causal chain is inferred when a link is absent" },
  { id: "model", title: "4. Model and stress-test an intervention", detail: "Apply an accepted-reading baseline deliberately, calculate server-owned scenario results, then show conservative/base/favorable sensitivity assumptions.", route: "/app/scenarios", action: "Open Scenarios", state: "Outputs are modeled—not a quotation, forecast, certification, or realized savings" },
  { id: "act", title: "5. Track accountable action and outcome evidence", detail: "Create or select a completed action with evidence. Lock the saved model to a matching baseline and a same-duration accepted-reading outcome window.", route: "/app/actions", action: "Open Actions", state: "Observed variance does not prove causation or financial realization" },
  { id: "report", title: "6. Export only what the records support", detail: "Select a stored evidence snapshot and show its targets, scenarios, comparisons, recommendations, simulation provenance, and non-certification disclosure.", route: "/app/reports", action: "Open Reports", state: "Executive evidence is record-bound, not certified ESG reporting" },
] as const;

export default function PresenterMode() {
  return <div className="ecosystem-page">
    <header className="workspace-header"><div><span className="ops-eyebrow"><span /> PRESENTER MODE</span><h1>Guide a judge through the evidence loop.</h1><p>A six-stage live narrative for EcoSphere AI: monitor, detect, predict, simulate, recommend, act, measure, and repeat—without presenting modeled or simulated records as real-world proof.</p></div><div className="tenant-badge"><ClipboardCheck size={18}/><span>6 stages</span><b>Evidence-led</b></div></header>
    <section className="workspace-panel" aria-label="Presenter flow"><header><div><span className="ops-eyebrow">LIVE DEMONSTRATION PATH</span><h2>One understandable operating story.</h2></div><Sparkles size={22}/></header><p>Move in order. Every handoff opens a valid authenticated workspace; use each stage’s state note to keep claims proportionate to the displayed record.</p><div className="compact-list">{stages.map((stage) => <article key={stage.id}><span>{stage.id.toUpperCase()}</span><b>{stage.title}</b><p>{stage.detail}</p><small><CircleAlert size={14}/> {stage.state}</small><a className="workspace-link" href={stage.route}>{stage.action} <ArrowUpRight size={15}/></a></article>)}</div></section>
    <section className="overview-grid">
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">JUDGE PROMPT</span><h2>What is real here?</h2></div><Gauge size={22}/></header><p>Tenant-scoped persisted readings, accepted-data rules, monitoring artifacts, scenario inputs and results, actions, outcome comparisons, and report snapshots are application records. Numerical outputs come from deterministic server calculations.</p><p className="muted">A deployed identity journey, durable scheduler execution, independent restore rehearsal, live hardware integration, and certified reporting remain external validation gates.</p></article>
      <article className="workspace-panel workspace-panel--signal"><header><div><span className="ops-eyebrow">RECOVERY PATH</span><h2>If a stage is empty</h2></div><CheckCircle2 size={22}/></header><p>Do not substitute invented state. Use the next useful-step guidance in the workspace: register a meter, ingest accepted evidence, run the controlled demo, save a scenario, create an action, or build a stored report snapshot.</p><a className="workspace-link" href="/app">Return to Operations Overview <ArrowUpRight size={15}/></a></article>
      <article className="workspace-panel"><header><div><span className="ops-eyebrow">PRESENTATION CLOSE</span><h2>Evidence, not theatrics.</h2></div><FileText size={22}/></header><p>Close on Reports with the model/factor/simulation disclosure visible. State that EcoSphere is a prototype sustainability operating system built to make evidence and limitations inspectable.</p></article>
    </section>
  </div>;
}
