import React, { useMemo, useState } from "react";
import { Download, Eye, FileText, Loader2, Printer, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useActiveOrganization } from "@/hooks/useActiveOrganization";
import { summarizeExecutiveEvidence } from "@/lib/executiveEvidence";
import { serializeSafeCsvRows } from "@/lib/csvSafety";

export default function ReportsWorkspace() {
  const utils = trpc.useUtils();
  const tenant = useActiveOrganization();
  const organizationId = tenant.organizationId ?? 0;
  const summary = trpc.reports.summary.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const snapshots = trpc.reports.snapshots.useQuery({ organizationId }, { enabled: Boolean(organizationId) });
  const [snapshotTitle, setSnapshotTitle] = useState("AIEM Campus operational evidence snapshot");
  const [notice, setNotice] = useState<string | null>(null);
  const [selectedSnapshotId, setSelectedSnapshotId] = useState<number | null>(null);
  const createSnapshot = trpc.reports.createSnapshot.useMutation({ onSuccess: async () => { await utils.reports.snapshots.invalidate({ organizationId }); setNotice("Evidence snapshot generated from the current tenant-scoped records."); }, onError: () => setNotice("Evidence snapshot was not generated. Retry the protected operation.") });

  function exportSelectedSnapshot() {
    if (!selectedSnapshot || !executive || !tenant.activeOrganization) return;
    const rows = [["EcoSphere AI stored evidence snapshot"], ["Organization", tenant.activeOrganization.organization.name], ["Snapshot ID", String(selectedSnapshot.id)], ["Snapshot generated at", executive.generatedAt], ["Evidence version", executive.version], ["Factor disclosure", executive.factorDisclosure], ["Modeled / certification boundary", "Modeled outputs are not certified sustainability disclosures or regulatory filings."], ["Simulation provenance", executive.hasSimulatedEvidence ? executive.demoDisclosure : "No simulated demo provenance was stored in this snapshot."], ["Stored target assessments", String(executive.targetAssessments.length)], ["Stored scenarios", String(executive.scenarioCount)], ["Stored comparisons", String(executive.comparisonCount)], ["Stored recommendations", String(executive.recommendationCount)]];
    const csv = serializeSafeCsvRows(rows);
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `ecosphere-evidence-snapshot-${selectedSnapshot.id}.csv`; link.click(); URL.revokeObjectURL(link.href);
  }

  function downloadEvidence(snapshot: { id: number; title: string; criteria: unknown; evidence: unknown; factorDisclosure: string; createdAt: Date }) {
    const content = JSON.stringify({ title: snapshot.title, criteria: snapshot.criteria, evidence: snapshot.evidence, factorDisclosure: snapshot.factorDisclosure, createdAt: snapshot.createdAt }, null, 2);
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "application/json" })); link.download = `ecosphere-evidence-snapshot-${snapshot.id}.json`; link.click(); URL.revokeObjectURL(link.href);
  }

  const selectedSnapshot = useMemo(() => snapshots.data?.find((snapshot) => snapshot.id === selectedSnapshotId) ?? null, [selectedSnapshotId, snapshots.data]);
  const executive = selectedSnapshot ? summarizeExecutiveEvidence(selectedSnapshot) : null;
  if (tenant.isLoading || summary.isLoading || snapshots.isLoading) return <div className="app-loading-state"><Loader2 className="animate-spin"/> Loading report boundary…</div>;
  if (tenant.error || summary.error || snapshots.error) return <section className="workspace-error"><span className="ops-eyebrow"><span /> REPORT UNAVAILABLE</span><h1>Operational records could not be summarized.</h1><p>No export is offered until the protected report query succeeds.</p><button onClick={() => { void summary.refetch(); void snapshots.refetch(); }}>Retry report query</button></section>;
  if (!tenant.activeOrganization) return <section className="empty-workspace"><span className="ops-eyebrow"><span /> REPORTING NEEDS EVIDENCE</span><h1>Nothing is reportable yet.</h1><p>Create an organization and establish a source registry before producing a scoped operational snapshot.</p></section>;
  const overview = summary.data?.overview;
  return <div className="ecosystem-page">
    <header className="workspace-header"><div><span className="ops-eyebrow"><span /> REPORTS</span><h1>Export only what the records support.</h1><p>Evidence snapshots preserve their criteria, persisted results, comparison evidence, and factor disclosure. They are not certified sustainability disclosures or regulatory filings; CSV cells are serialized as literal text to avoid spreadsheet formula execution.</p></div><button className="export-button" onClick={exportSelectedSnapshot} disabled={!selectedSnapshot || !executive}><Download size={16}/> Export selected evidence CSV</button></header>
    {notice && <div className="workbench-notice" role="status">{notice}</div>}
    <section className="report-sheet"><div className="report-sheet__stamp"><FileText size={27}/><span>OPERATIONAL SNAPSHOT</span><b>Tenant scoped</b></div><div className="report-stats"><div><span>SITES</span><b>{overview?.siteCount ?? 0}</b></div><div><span>METERS</span><b>{overview?.meterCount ?? 0}</b></div><div><span>READINGS</span><b>{overview?.readingCount ?? 0}</b></div><div><span>ACTIONS</span><b>{overview?.actionCount ?? 0}</b></div></div><div className="report-disclaimer"><ShieldCheck size={20}/><p>Scope: tenant registry, persisted readings, ingestion history, tracked actions, saved forecasts, recommendations, and comparisons only when they exist in the database. Carbon calculations retain their factor disclosures and pilot limitations.</p></div></section>
    <section className="workspace-panel"><header><div><span className="ops-eyebrow">EVIDENCE-GRADE SNAPSHOT</span><h2>Freeze the records behind a report</h2></div><FileText size={22}/></header><p>Generation stores the report criteria and evidence payload server-side. The downloadable JSON and executive view use that stored snapshot; neither recalculates a client claim.</p><div className="workspace-actions"><input aria-label="Evidence snapshot title" value={snapshotTitle} onChange={(event) => setSnapshotTitle(event.target.value)} minLength={3}/><button disabled={createSnapshot.isPending || snapshotTitle.trim().length < 3} onClick={() => createSnapshot.mutate({ organizationId, title: snapshotTitle.trim() })}>{createSnapshot.isPending ? "Generating snapshot…" : "Generate evidence snapshot"}</button></div>{createSnapshot.error ? <p role="alert" className="form-error">{createSnapshot.error.message}</p> : null}{snapshots.data?.length ? <div className="compact-list">{snapshots.data.map((snapshot) => <div key={snapshot.id}><span>#{snapshot.id} · {new Date(snapshot.createdAt).toLocaleString()}</span><b>{snapshot.title}</b><small>{snapshot.factorDisclosure}</small><div className="workspace-actions"><button onClick={() => setSelectedSnapshotId(snapshot.id)}><Eye size={16}/> View executive evidence</button><button onClick={() => downloadEvidence(snapshot)}>Download stored JSON</button></div></div>)}</div> : <p>No evidence snapshot exists for this tenant yet.</p>}</section>
    {selectedSnapshot && executive ? <section className="workspace-panel workspace-panel--wide executive-evidence-report" aria-label="Executive evidence report"><header><div><span className="ops-eyebrow">EXECUTIVE EVIDENCE VIEW</span><h2>{selectedSnapshot.title}</h2></div><button onClick={() => window.print()}><Printer size={16}/> Print current view</button></header><div className="executive-evidence-print-disclosure"><b>STORED TENANT EVIDENCE — NOT CERTIFIED</b><span>{tenant.activeOrganization.organization.name} · snapshot #{selectedSnapshot.id} · {executive.generatedAt} · {executive.version}</span><span>Factor: {executive.factorDisclosure}</span><span>{executive.hasSimulatedEvidence ? executive.demoDisclosure : "No simulated demo provenance was stored in this snapshot."}</span></div><p>Snapshot #{selectedSnapshot.id} · {executive.generatedAt} · {executive.version}. This view presents stored tenant-bound evidence only.</p><div className="report-stats"><div><span>TARGETS</span><b>{executive.targetAssessments.length}</b></div><div><span>SCENARIOS</span><b>{executive.scenarioCount}</b></div><div><span>COMPARISONS</span><b>{executive.comparisonCount}</b></div><div><span>RECOMMENDATIONS</span><b>{executive.recommendationCount}</b></div></div>{executive.targetAssessments.length ? <div className="compact-list">{executive.targetAssessments.map((target) => <div key={`${target.metric}-${target.label}`}><span>{target.metric.toUpperCase()} · {target.state.replaceAll("_", " ")}</span><b>{target.label}</b><small>{target.achievedValue ?? "Not recorded"} / {target.targetValue ?? "Not recorded"} {target.unit} · evidence {target.freshness}</small></div>)}</div> : <p>No active target assessments were stored in this snapshot.</p>}{executive.sdgContributions.length ? <div className="compact-list">{executive.sdgContributions.map((impact) => <div key={`${impact.sdg}-${impact.title}`}><span>MODELED SDG {impact.sdg ?? "—"}</span><b>{impact.title}</b><small>{impact.index ?? "Not recorded"}/100 pilot modeled contribution index; not certified achievement.</small></div>)}</div> : <p>No modeled SDG contribution was stored in this snapshot.</p>}<div className="report-disclaimer"><ShieldCheck size={20}/><p>{executive.factorDisclosure} {executive.hasSimulatedEvidence ? executive.demoDisclosure : "No simulated demo provenance was stored in this snapshot."}</p></div></section> : null}
    <section className="workspace-panel"><span className="ops-eyebrow">INGESTION HISTORY</span><h2>Recent source submissions</h2>{summary.data?.recentBatches.length ? <div className="compact-list">{summary.data.recentBatches.map((batch) => <div key={batch.id}><span>#{batch.id} · {batch.source}</span><b>{batch.acceptedRows}/{batch.totalRows} accepted</b><small>{batch.status}</small></div>)}</div> : <p>No ingestion batch has been recorded for this tenant.</p>}</section>
  </div>;
}
